# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f4304f03c12019f43c368afb676b9be45ab1a587ea3744a94c42bb736555f4c73b969c57ef2d955f41055b49c7393b4a371ea2e280e015fd645ba2d3e145867

test:
  secret_key_base: ea0e3a0c7c5312b924378e388a8f1df9319dfb5e5cee17038423629e60479d97f22a6ec58b6f3cccb0b089b2c5b8f687374a308c3a4a03d58d8067ea46b6b4be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
